### ISSUE TITLE
Thoughts on AV1?

### ISSUE THREAD

**Issue by synaestheory** [Jeff425/bevy_h264#2]
Since h264 has patent/license implications, what do you think about supporting AV1 which is open and royalty free? Is it considered out of scope given the name of the crate?

**Comment by Jeff425** [comment]
I looked into AV1 and VP9 which also have their own patent issues, and AV1 still seems like there's not much device support. I decided just to focus on h264 since the patents will start to expire soon.

Video files in general are just a mess :(

With that in mind, this crate won't support any other files, but if any other crate wants to use my work to make a more general purpose crate that is fine with me too.
